name: adopptrs
channels:
  - pytorch
  - defaults
dependencies:
  - jupyter=1.0.0
  - numpy=1.18.1
  - pip=20.0.2
  - python=3.8.2
  - pytorch=1.4.0
  - scipy=1.4.1
  - pip:
    - matplotlib==3.2.1
    - opencv-python==4.2.0.32
    - owslib==0.19.2
    - pandas==1.0.3
    - pillow==7.0.0
    - torchsummary==1.5.1
    - torchvision==0.5.0
